Vagrant.configure("2") do |config|
  
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.box_check_update = false
  
    config.vm.define "kfaouziS" do |server|
      server.vm.hostname = "kfaouziS"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.name = "kfaouziS"
        vb.memory = 512
        vb.cpus = 1
      end
      config.vm.provision "file", source: "./confs", destination: "~/confs"
      server.vm.provision "shell", path: "scripts/server.sh", privileged: true, run: 'always'  
    end
end